version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_NAME=Crypto Casino
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=casino
      - DB_USERNAME=casino_user
      - DB_PASSWORD=casino_password
    depends_on:
      - db
    volumes:
      - ./storage:/var/www/html/storage

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=casino
      - MYSQL_USER=casino_user
      - MYSQL_PASSWORD=casino_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
